version: '3.7'

services:
  db:
    image: postgres:11-alpine
    env_file:
      - docker.env
    ports:
      - "5433:5432"

  backend:
    depends_on:
      - db
      - d-transformer
      - u-transformer
    image: sumanthrudder/rudder-server

    entrypoint: sh -c './wait-for db:5432 -- rudder-server'

    ports:
      - "8080:8080"
    env_file:
      - docker.env

  d-transformer:
    image: sumanthrudder/rudder-dest-transformer 
    ports:
      - "9090:9090"
    env_file:
      - docker.env

  u-transformer:
    image: sumanthrudder/rudder-user-transformer 
    ports:
      - "9292:9292"
    env_file:
      - docker.env
